package com.pheth.hasee.stickerhero.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pheth.hasee.stickerhero.greendao.Favorite;
import com.pheth.hasee.stickerhero.greendao.History;
import com.pheth.hasee.stickerhero.greendao.FavoriteCategory;

import com.pheth.hasee.stickerhero.greendao.FavoriteDao;
import com.pheth.hasee.stickerhero.greendao.HistoryDao;
import com.pheth.hasee.stickerhero.greendao.FavoriteCategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig favoriteCategoryDaoConfig;

    private final FavoriteDao favoriteDao;
    private final HistoryDao historyDao;
    private final FavoriteCategoryDao favoriteCategoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        favoriteCategoryDaoConfig = daoConfigMap.get(FavoriteCategoryDao.class).clone();
        favoriteCategoryDaoConfig.initIdentityScope(type);

        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        favoriteCategoryDao = new FavoriteCategoryDao(favoriteCategoryDaoConfig, this);

        registerDao(Favorite.class, favoriteDao);
        registerDao(History.class, historyDao);
        registerDao(FavoriteCategory.class, favoriteCategoryDao);
    }
    
    public void clear() {
        favoriteDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        favoriteCategoryDaoConfig.getIdentityScope().clear();
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public FavoriteCategoryDao getFavoriteCategoryDao() {
        return favoriteCategoryDao;
    }

}
