package com.pheth.hasee.stickerhero.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FAVORITE".
 */
public class Favorite {

    private Long id;
    private String name;
    private String url_full;
    private String url_thumb;
    private String search_id;
    private String url_full_local;
    private String url_thumb_local;
    private java.util.Date add_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Favorite() {
    }

    public Favorite(Long id) {
        this.id = id;
    }

    public Favorite(Long id, String name, String url_full, String url_thumb, String search_id, String url_full_local, String url_thumb_local, java.util.Date add_date) {
        this.id = id;
        this.name = name;
        this.url_full = url_full;
        this.url_thumb = url_thumb;
        this.search_id = search_id;
        this.url_full_local = url_full_local;
        this.url_thumb_local = url_thumb_local;
        this.add_date = add_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl_full() {
        return url_full;
    }

    public void setUrl_full(String url_full) {
        this.url_full = url_full;
    }

    public String getUrl_thumb() {
        return url_thumb;
    }

    public void setUrl_thumb(String url_thumb) {
        this.url_thumb = url_thumb;
    }

    public String getSearch_id() {
        return search_id;
    }

    public void setSearch_id(String search_id) {
        this.search_id = search_id;
    }

    public String getUrl_full_local() {
        return url_full_local;
    }

    public void setUrl_full_local(String url_full_local) {
        this.url_full_local = url_full_local;
    }

    public String getUrl_thumb_local() {
        return url_thumb_local;
    }

    public void setUrl_thumb_local(String url_thumb_local) {
        this.url_thumb_local = url_thumb_local;
    }

    public java.util.Date getAdd_date() {
        return add_date;
    }

    public void setAdd_date(java.util.Date add_date) {
        this.add_date = add_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
