package com.pheth.hasee.stickerhero.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.pheth.hasee.stickerhero.greendao.History;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY".
*/
public class HistoryDao extends AbstractDao<History, Long> {

    public static final String TABLENAME = "HISTORY";

    /**
     * Properties of entity History.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Url_send_local = new Property(2, String.class, "url_send_local", false, "URL_SEND_LOCAL");
        public final static Property Url_send_online = new Property(3, String.class, "url_send_online", false, "URL_SEND_ONLINE");
        public final static Property Url_thumb_local = new Property(4, String.class, "url_thumb_local", false, "URL_THUMB_LOCAL");
        public final static Property Url_thumb_online = new Property(5, String.class, "url_thumb_online", false, "URL_THUMB_ONLINE");
        public final static Property Identifier = new Property(6, String.class, "identifier", false, "IDENTIFIER");
        public final static Property Add_date = new Property(7, java.util.Date.class, "add_date", false, "ADD_DATE");
    };


    public HistoryDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"URL_SEND_LOCAL\" TEXT," + // 2: url_send_local
                "\"URL_SEND_ONLINE\" TEXT," + // 3: url_send_online
                "\"URL_THUMB_LOCAL\" TEXT," + // 4: url_thumb_local
                "\"URL_THUMB_ONLINE\" TEXT," + // 5: url_thumb_online
                "\"IDENTIFIER\" TEXT," + // 6: identifier
                "\"ADD_DATE\" INTEGER);"); // 7: add_date
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, History entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String url_send_local = entity.getUrl_send_local();
        if (url_send_local != null) {
            stmt.bindString(3, url_send_local);
        }
 
        String url_send_online = entity.getUrl_send_online();
        if (url_send_online != null) {
            stmt.bindString(4, url_send_online);
        }
 
        String url_thumb_local = entity.getUrl_thumb_local();
        if (url_thumb_local != null) {
            stmt.bindString(5, url_thumb_local);
        }
 
        String url_thumb_online = entity.getUrl_thumb_online();
        if (url_thumb_online != null) {
            stmt.bindString(6, url_thumb_online);
        }
 
        String identifier = entity.getIdentifier();
        if (identifier != null) {
            stmt.bindString(7, identifier);
        }
 
        java.util.Date add_date = entity.getAdd_date();
        if (add_date != null) {
            stmt.bindLong(8, add_date.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public History readEntity(Cursor cursor, int offset) {
        History entity = new History( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url_send_local
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // url_send_online
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // url_thumb_local
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // url_thumb_online
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // identifier
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)) // add_date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, History entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrl_send_local(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrl_send_online(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrl_thumb_local(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUrl_thumb_online(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIdentifier(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAdd_date(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(History entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(History entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
