package com.pheth.hasee.stickerhero.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HISTORY".
 */
public class History {

    private Long id;
    private String name;
    private String url_send_local;
    private String url_send_online;
    private String url_thumb_local;
    private String url_thumb_online;
    private String identifier;
    private java.util.Date add_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    public History(Long id, String name, String url_send_local, String url_send_online, String url_thumb_local, String url_thumb_online, String identifier, java.util.Date add_date) {
        this.id = id;
        this.name = name;
        this.url_send_local = url_send_local;
        this.url_send_online = url_send_online;
        this.url_thumb_local = url_thumb_local;
        this.url_thumb_online = url_thumb_online;
        this.identifier = identifier;
        this.add_date = add_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl_send_local() {
        return url_send_local;
    }

    public void setUrl_send_local(String url_send_local) {
        this.url_send_local = url_send_local;
    }

    public String getUrl_send_online() {
        return url_send_online;
    }

    public void setUrl_send_online(String url_send_online) {
        this.url_send_online = url_send_online;
    }

    public String getUrl_thumb_local() {
        return url_thumb_local;
    }

    public void setUrl_thumb_local(String url_thumb_local) {
        this.url_thumb_local = url_thumb_local;
    }

    public String getUrl_thumb_online() {
        return url_thumb_online;
    }

    public void setUrl_thumb_online(String url_thumb_online) {
        this.url_thumb_online = url_thumb_online;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public java.util.Date getAdd_date() {
        return add_date;
    }

    public void setAdd_date(java.util.Date add_date) {
        this.add_date = add_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
